version: "3.7"
services:
  app-name:
    build:
      context: .
    image: app-name
    container_name: app-name
    ports:
      - "127.0.0.01:8050:8050"
    environment:
      - TARGET=$TARGET
    restart: unless-stopped